### ISSUE TITLE
Loop fusion

### ISSUE THREAD

**Issue by Demi-Marie** [graydon/newel#1]
This can dramatically improve cache usage.

**Comment by graydon** [comment]
@DemiMarie-parity Hmm, I'm not sure. I think the general idea with vectorized interpreters is you pipeline a single L1-cache-worth of data through multiple operators before recycling the storage. Fusing loops at a code level would cause significant combinatorial expansion of the operator set. Keep in mind this is not a JIT, that's the whole point -- we're AOT compiling all the loops.

Or am I misunderstanding? What sort of loop fusion do you have in mind?

**Comment by Demi-Marie** [comment]
By loop fusion, I mean doing as much as possible for each loop iteration, avoiding the creation of temporary vectors.  Image processing pipelines often represent the operations to be done as a graph.

**Comment by graydon** [comment]
Yes I understand the general principle of loop fusion. I'm saying that "an iteration" in this design is "32kb of data", which you process entirely in one opertor, and then hand to another operator (while it's still in cache). And the hand-off between those operators is done dynamically -- using interpretation, virtual methods, etc. -- not statically.

Obviously if you tried to fuse operators dynamically like that on a scalar-by-scalar basis, it'd be prohibitively costly: you'd spend as much time calculating the next operator to apply as you spend applying it. But the whole point of this crate is that if you batch your operators to a relatively large scale (all the way up to the size of the L1 cache) you can _amortize out_ the cost of dynamic composition, making _one_ dynamic-composition decision every 32,000 useful-work operations. This is cheap enough that there's no big benefit to specializing statically.

And this matters for implementation complexity. If you try to fuse at a _fine_ grain, you _have_ to do it statically (it's too costly at runtime to do so dynamically); but then if you try to fuse statically _ahead of time_ you can't: you wind up having to make too many static combinations. Like you make a combined operator for add+compare, then add+div, then add+mul, then div+compare, then div+mul, ... you wind up having to AOT-compile `(nOps * nTypes) ** (nFuseDepth)` fused-operators. It's overwhelming very quickly. So instead you get forced to JIT, generating only the fusions the user wants, but at runtime. And writing a JIT is expensive and complicated.

The idea of this crate (which is widely practiced by other systems!) is to go with the simpler route: dynamically compose your operator graph, and amortize the dynamic composition costs by choosing a large-ish chunk size. Not so large that you start spilling out of the cache, but large enough to amortize.

There's empirical work to back this up. If you look at the referenced paper (http://www.vldb.org/pvldb/vol11/p2209-kersten.pdf) you'll see that their "TectorWise" implementation (a clone of VectorWise -- which does what this crate does) runs almost as fast on most queries as their "Typer" implementation (a clone of HyPer -- which implements a much more complex specializing and op-fusing JIT). Because the composition points are rare relative to the very-fast vectorized inner loops. You do have to be careful to choose the chunk size to have good cache-affinity, but that's really the only delicate part. See figure 5 in the paper, somewhere between 1kb-32kb (the size of the L1 cache) is ideal: you get the amortization effects without bringing in new cache-miss effects as chunks move through the graph.

Does that all make sense?

**Comment by Demi-Marie** [comment]
It does, indeed.  Thank you!
